### ISSUE TITLE
Problem downloading LORIOT binary

### ISSUE THREAD

**Issue by rainierwolfcastle** [ARMmbed/lora-docs#2]
Robert Taylor [3:34 PM] 
I’m trying to copy over the loraiot binary

Jan Jongboom [3:34 PM] 
yeah so the idea is you enable DHCP through microUSB

[3:34] 
then connect to normal network and do everything else over SSH (edited)

[3:35] 
cause i dunno how to copy a file using screen

Robert Taylor [3:36 PM] 
I have dhcp enabled

[3:37] 
and I can ping things from the conduir

[3:37] 
ifconfig gives me the IP address: 10.2.202.22

[3:37] 
but I can’t ssh into it

Jan Jongboom [3:37 PM] 
k, so ssh root@10.2.202.22 should log you in

[3:37] 
hmm

Robert Taylor [3:37 PM] 
ssh root@10.2.202.22

[3:38] 
just hanging

[3:38] 
bobbys-air:connector_channel taylorr$ ssh root@10.2.202.22 -v
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /Users/taylorr/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 20: Applying options for *
debug1: /etc/ssh/ssh_config line 53: Applying options for *
debug1: Connecting to 10.2.202.22 [10.2.202.22] port 22.

Jan Jongboom [3:38 PM] 
myeah maybe this revision doesnt have dropbear?

[3:38] 
or another ssh server

Robert Taylor [3:38 PM] 
I haven’t tried to upgrade the firmware on it

[3:38] 
I imagine it might be pretty old given it’s an eval box

Jan Jongboom [3:39 PM] 
myeah

[3:39] 
does it have curl?

Robert Taylor [3:39 PM] 
yes

new messages
Jan Jongboom [3:39 PM] 
you could download the binary with Chrome w/ network panel open

[3:39] 
I think it has a 'copy as curl' command

[3:39] 
then download it using that

Robert Taylor [3:44 PM] 
behind a login wall

[3:44] 
gah

Jan Jongboom [3:44 PM] 
thats why you need the copy as curl

[3:44] 
it copies cookies as well

Robert Taylor [3:45 PM] 
can’t find it

[3:45] 
got it

Jan Jongboom [3:45 PM] 
uploaded an image: Pasted image at 2016-04-05, 4:45 PM 
Add Comment
Robert Taylor [3:45 PM] 
yeah, found it

[3:45] 
thanks

[3:46] 
doesn’t seem to download it

[3:47] 
even on my desktop

Jan Jongboom [3:47 PM] 
whats the command?

Robert Taylor [3:47 PM] 
bobbys-air:Desktop taylorr$ curl 'https://www.loriot.io/home/gwsw/loriot_multitech_conduit_mCard_USB_1.0.1.tgz' -H 'DNT: 1' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,​_/_​;q=0.8' -H 'Referer: https://www.loriot.io/home/gateways.html' -H 'Cookie: sessionid=' -H 'Connection: keep-alive' -H 'If-Range: W/"1b752-153ba114440"' -H 'Range: bytes=2854-2854' --compressed -v
-   Trying 52.28.250.46...
- Connected to www.loriot.io (52.28.250.46) port 443 (#0)
- TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
- Server certificate: *.loriot.io
- Server certificate: RapidSSL SHA256 CA - G3
- Server certificate: GeoTrust Global CA
  > GET /home/gwsw/loriot_multitech_conduit_mCard_USB_1.0.1.tgz HTTP/1.1
  > Host: www.loriot.io
  > DNT: 1
  > Accept-Encoding: gzip, deflate, sdch
  > Accept-Language: en-US,en;q=0.8
  > Upgrade-Insecure-Requests: 1
  > User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
  > Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,​_/_​;q=0.8
  > Referer: https://www.loriot.io/home/gateways.html
  > Cookie: sessionid=
  > Connection: keep-alive
  > If-Range: W/"1b752-153ba114440"
  > Range: bytes=2854-2854
  >
  < HTTP/1.1 206 Partial Content
  < Accept-Ranges: bytes
  < Cache-Control: public, max-age=0
  < Last-Modified: Sun, 27 Mar 2016 21:53:27 GMT
  < ETag: W/"1b752-153ba114440"
  < Content-Type: application/octet-stream
  < Content-Range: bytes 2854-2854/112466
  < Content-Length: 1
  < Date: Tue, 05 Apr 2016 14:47:18 GMT
  < Connection: keep-alive
  < 
- Connection #0 to host www.loriot.io left intact
  ?bobbys-air:Desktop taylorr$

Jan Jongboom [3:48 PM] 
hmpf

[3:51] 
try this

wget https://www.loriot.io/home/gwsw/loriot_multitech_conduit_mCard_USB_1.0.1.tgz --header='Cookie: sessionid=' (edited)

Robert Taylor [3:55 PM] 
worked

[3:55] 
gateway is connected!

**Comment by janjongboom** [comment]
This is now fixed by LORIOT
